# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/headlessbear/projects/PokerParlor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/headlessbear/projects/PokerParlor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/headlessbear/projects/PokerParlor/CMakeFiles /home/headlessbear/projects/PokerParlor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/headlessbear/projects/PokerParlor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named poker_bot

# Build rule for target.
poker_bot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poker_bot
.PHONY : poker_bot

# fast build rule for target.
poker_bot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/build
.PHONY : poker_bot/fast

src/deck/card.o: src/deck/card.cpp.o
.PHONY : src/deck/card.o

# target to build an object file
src/deck/card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/deck/card.cpp.o
.PHONY : src/deck/card.cpp.o

src/deck/card.i: src/deck/card.cpp.i
.PHONY : src/deck/card.i

# target to preprocess a source file
src/deck/card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/deck/card.cpp.i
.PHONY : src/deck/card.cpp.i

src/deck/card.s: src/deck/card.cpp.s
.PHONY : src/deck/card.s

# target to generate assembly for a file
src/deck/card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/deck/card.cpp.s
.PHONY : src/deck/card.cpp.s

src/deck/deck.o: src/deck/deck.cpp.o
.PHONY : src/deck/deck.o

# target to build an object file
src/deck/deck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/deck/deck.cpp.o
.PHONY : src/deck/deck.cpp.o

src/deck/deck.i: src/deck/deck.cpp.i
.PHONY : src/deck/deck.i

# target to preprocess a source file
src/deck/deck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/deck/deck.cpp.i
.PHONY : src/deck/deck.cpp.i

src/deck/deck.s: src/deck/deck.cpp.s
.PHONY : src/deck/deck.s

# target to generate assembly for a file
src/deck/deck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/deck/deck.cpp.s
.PHONY : src/deck/deck.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/player/player.o: src/player/player.cpp.o
.PHONY : src/player/player.o

# target to build an object file
src/player/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/player/player.cpp.o
.PHONY : src/player/player.cpp.o

src/player/player.i: src/player/player.cpp.i
.PHONY : src/player/player.i

# target to preprocess a source file
src/player/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/player/player.cpp.i
.PHONY : src/player/player.cpp.i

src/player/player.s: src/player/player.cpp.s
.PHONY : src/player/player.s

# target to generate assembly for a file
src/player/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/poker_bot.dir/build.make CMakeFiles/poker_bot.dir/src/player/player.cpp.s
.PHONY : src/player/player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... poker_bot"
	@echo "... src/deck/card.o"
	@echo "... src/deck/card.i"
	@echo "... src/deck/card.s"
	@echo "... src/deck/deck.o"
	@echo "... src/deck/deck.i"
	@echo "... src/deck/deck.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/player/player.o"
	@echo "... src/player/player.i"
	@echo "... src/player/player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

